name: expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_notch_bottom_bar: ^1.0.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0  
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  icons_plus: ^5.0.0
  firebase_auth: ^5.3.3
  pie_chart: ^5.4.0
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  intl: ^0.18.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpeg"
  adaptive_icon_foreground: "assets/images/1024.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
   - assets/images/
